### ISSUE TITLE
:dna: [FEATURE] - Check and Implement `public` GitHub Repository Features :dna:

### ISSUE THREAD

**Issue by xKabbe** [xKabbe/denigma#7]
# Description
Since the repository is now `public` and not `private`, we have significantly more features available, such as:

* More than 3 contributors can work at the project (shouldn't be relevant for this project)
* Apply branch protection rules (e.g. merge request rules, etc.)
* Enable `GitHub Pages`
* Enable project wiki
* Enable most of the `Insights` functionalities
* Add badges from [Shields IO](https://shields.io)
* Enable `Draft Pull Request` feature

# Additional Context (Screenshots, Logs, ...)
* [Shields IO](https://shields.io) - A service for concise, consistent, and legible badges in SVG and raster format

# Expected Actions
* [x] Applied some of the advantages named above:
  * [x] Added badges
  * [x] Applied branch protection rules
  * [x] Enabled `Draft Pull Request`
  * [x] ...

# Definition of Done
* [x] Added new functionalities

**Comment by xKabbe** [comment]
Adding code coverage was a little bit tricky without any prior knowledge. In the end, I was able to add code coverage by using [Coveralls](https://coveralls.io/). For the future, these tips could possibly be helpful:

1. Add the public repo on [coveralls.io](https://coveralls.io/)
2. It's not directly necessary to use the coveralls repo token, since `GitHub Actions` supports the whole process with `coveralls` via `secrets.GITHUB_TOKEN`
3. The `npm test` command should create a `lcov.info` file with the coverage as content. The `--coverage` and `coverageDirectory=...` need to be used like (in `package.json`):
```json
"test": "env-cmd --no-override -f ./.env-override/.env.test react-scripts test --env=jsdom --coverage --coverageDirectory='./out/coverage' --watchAll=false"
```
4. Create a new test step in the `GitHub Actions` workflow file after running `npm test`, which should post the created coverage to the coveralls API
```yml
name: Test React Application
run-name: ${{ github.actor }} is testing 🧪 the React Application 💻

# Controls when the action will run.
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # ID of the job
  react-jest-test:
    # Name of the job as it will be displayed in GitHub
    name: React Jest Test 🧪
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies 🪜
        run: npm ci
      - name: Run Jest Tests 🪜
        run: npm test
      - name: Post Coverage to Coveralls 🪜
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./out/coverage/lcov.info
```
6. Besides the important usage of `uses: coverallsapp/github-action@master` it is a must to verify that the test coverage is send to the correct coverall repo. This is verified via `github-token: ${{ secrets.GITHUB_TOKEN }}`. But the most important part is the `path-to-lcov` that has to match the path to the created lcov.info file. Otherwise it can't find the report.

> **Note**
> It is also possible to post the test coverage for local executed tests. By creating a `.coveralls.yml` with the content
> ```yml
> repo_token: xxxxxxxxxxxx
> ```
> at the projects root level, it's possible to run something like (in `package.json`)
> ```json
> "test:coveralls": "env-cmd --no-override -f ./.env-override/.env.test react-scripts test --env=jsdom --coverage --coverageDirectory='./out/coverage' --watchAll=false && coveralls < ./out/coverage/lcov.info"
> ```
> but it's crucial not to add the actual token into the remote repository.
